version: '3'

services:
  app:
    build:
      context: .
    # =========ローカルと本番切り替え===========
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
    # ======================================
    volumes:
      - .:/badsearch
      - public-data:/badsearch/public
      - tmp-data:/badsearch/tmp
      - log-data:/badsearch/log
    tty: true
    stdin_open: true
  # =========本番はコメントアウト============
    # depends_on:
    #   - db
 
  # db:
  #   image: mysql:5.6.51
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USERNAME}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     TZ: "Asia/Tokyo"
  #     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  #   ports:
  #     - "4306:3306"
  #   volumes:
  #     - db-data:/var/lib/mysql
  # ======================================

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/badsearch/public
      - tmp-data:/badsearch/tmp
      # - gem_data:/usr/local/bundle
    ports:
      - 80:80
    depends_on:
      - app


volumes:
  public-data:
  tmp-data:
  log-data:
  # gem_data:
  # db-data:  #本番はコメントアウト