version: '3'

services:

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/badsearch/public
      - tmp-data:/badsearch/tmp
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/badsearch
      - public-data:/badsearch/public
      - tmp-data:/badsearch/tmp
      - log-data:/badsearch/log
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql:5.6.51
    environment:
      MY_SQL: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:./tmp/db:/var/lib/mysql/data

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
