version: '3'

services:
  db:
    image: mysql:5.6.51
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql/data

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/badsearch/
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mysql_data: